### ISSUE TITLE
No arranca

### ISSUE THREAD

**Issue by jmmanzano** [atareao/remote-raspberry#1]
He instalado la aplicación no arranca.
Primero he instalado una dependencia que al parecer faltaba (python3-plumbum).
Tras esto vuelvo a intentar iniciarla y sigue sin arrancar.
Desde consola me muestra lo siguiente:
```
josemi@levono:~$ remote-raspberry 
Traceback (most recent call last):
  File "/usr/share/remote-raspberry/application.py", line 117, in do_activate
    window = MainWindow(self)
  File "/usr/share/remote-raspberry/mainwindow.py", line 115, in __init__
    self.raspberryMemory = RaspberryMemory(self)
  File "/usr/share/remote-raspberry/raspberry_memory.py", line 63, in __init__
    self.__set_ui()
  File "/usr/share/remote-raspberry/raspberry_memory.py", line 209, in __set_ui
    self.load_information()
  File "/usr/share/remote-raspberry/raspberry_memory.py", line 215, in load_information
    self.raspberryClient.connect()
  File "/usr/share/remote-raspberry/raspberry_client.py", line 57, in connect
    raise Exception(_('Hostname must be set'))
Exception: Introduce el hostname
```
Un saludo.

**Comment by jmmanzano** [comment]
No iniciaba porque en el json de configuración inicial no está bien informado y sin este fichero bien informado no se consigue iniciar la aplicación.

Hay que editar el fichero  remote-rasberry.json que está en la ruta ~/.config/remote-raspberry para que arranque la aplicación.

**Comment by atareao** [comment]
Muchas gracias @jmmanzano . Corregido
